# source director
APP_DRIVER_DIR = $(APP_DIR)/driver
APP_DRIVER_SRC_DIR = $(APP_DIR)/driver/src
APP_DRIVER_INC_DIR = $(APP_DIR)/driver/include

# app
SRC  += $(APP_DIR)/main.c
SRC  += $(APP_DRIVER_SRC_DIR)/stx_uart2.c
SRC  += $(APP_DRIVER_SRC_DIR)/stx_uart_shell.c
SRC  += $(APP_DRIVER_SRC_DIR)/shell_cmd_ps.c
SRC  += $(APP_DRIVER_SRC_DIR)/shell_ps_info/tsk_info.c
SRC  += $(APP_DRIVER_SRC_DIR)/shell_ps_info/mtx_info.c
SRC  += $(APP_DRIVER_SRC_DIR)/shell_ps_info/profile_info.c
SRC  += $(APP_DRIVER_SRC_DIR)/shell_cmd_sleep.c
SRC  += $(APP_DRIVER_SRC_DIR)/shell_cmd_reboot.c
SRC  += $(APP_DRIVER_SRC_DIR)/shell_cmd_time.c

# include directories
INCLUDE_DIRS += $(APP_DRIVER_INC_DIR)

