# source director
APP_DRIVER_DIR = $(APP_DIR)/driver
APP_DRIVER_SRC_DIR = $(APP_DIR)/driver/src
APP_DRIVER_INC_DIR = $(APP_DIR)/driver/include

# app
SRC  += $(APP_DIR)/main.c
SRC  += $(APP_DRIVER_SRC_DIR)/stx_uart2.c
SRC  += $(APP_DRIVER_SRC_DIR)/stx_uart_shell.c


# include directories
INCLUDE_DIRS += $(APP_DRIVER_INC_DIR)

